name: periodtracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_calendar: ^29.2.11+1
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/backgrounddark.jpg
    - assets/images/backgroundlight.jpg

# Keep this for other flutter_gen features (colors, fonts, etc.)
flutter_gen:
  output: lib/gen/
  colors:
    enabled: true
  fonts:
    enabled: true
  integrations:
    flutter_svg: true

# Keep this for material localization support
flutter_localizations:
  sdk: flutter