name: Flutter CI/CD (Android + iOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter (3.32.5)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'  # Contains Dart 3.8.1
          cache: true

      - name: Verify versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage

  build-android:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - run: flutter build apk --release
      - run: flutter build appbundle --release

  build-ios:
    needs: test
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
      - run: |
          flutter build ios --config-only
          xcodebuild build \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO
