name: Flutter CI/CD (Android + iOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Build Android (Linux runner only)
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      - name: Build iOS (macOS runner only)
        if: matrix.os == 'macos-latest'
        run: |
          flutter build ios --config-only --no-codesign
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO \
            DSTROOT=build/ios \
            OBJROOT=build/ios \
            SYMROOT=build/ios \
            ONLY_ACTIVE_ARCH=YES