name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # First try to format automatically (non-fatal)
      - name: Attempt automatic formatting
        run: |
          echo "Running automatic formatting..."
          dart format .
          git diff --quiet || (
            echo "::warning::Some files were automatically formatted"
            echo "Please run 'dart format .' locally and commit the changes"
          )

      # Then verify no additional formatting needed (fatal)
      - name: Verify formatting
        run: |
          echo "Verifying code formatting..."
          dart format --output=none --set-exit-if-changed .
          echo "✓ Formatting is correct!"

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS (simulator)
        run: flutter build ios --simulator --no-codesign
