name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'  # Or your required version
          cache: true

      - name: Verify Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Corrected format command:
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS (simulator)
        run: flutter build ios --simulator --no-codesign
