name: Flutter CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'  # Use your required version
          cache: true

      - name: Verify Flutter version
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      # Correct formatting check for modern Flutter versions
      - name: Check code formatting
        run: |
          echo "Checking code formatting..."
          dart format --output=none --set-exit-if-changed .
          echo "✓ Formatting looks good!"

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test --coverage

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build iOS (simulator)
        run: flutter build ios --simulator --no-codesign

      # Optional coverage upload
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: success()
